import React from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import rehypeSlug from "rehype-slug";
import rehypeAutolinkHeadings from "rehype-autolink-headings";
import { StatusBadge } from "@/components/status-badge";
const STATUS=/^(🟢|🟡|🔴|⚪)(?:\s+(.+))?$/;
const RACI=/^(R|A|C|I|—)$/;
type ListKind="activities"|"actions"|"deliverables"|"deliveries"|"dependencies"|"critical-assets"|"milestones"|"risks"|"default";
function childrenText(children:React.ReactNode):string{return React.Children.toArray(children).map((child)=>{if(typeof child==="string"||typeof child==="number")return String(child);if(React.isValidElement<{children?:React.ReactNode}>(child))return childrenText(child.props.children);return""}).join("").trim()}
function calloutClass(text:string){const value=text.toLowerCase();if(value.includes("puede comenzar")||value.includes("puede hacer marketing"))return"semantic-callout callout-positive";if(value.includes("todavía no puede")||value.includes("qué bloquea")||value.includes("activos críticos"))return"semantic-callout callout-danger";if(value.includes("próximo gran hito"))return"semantic-callout callout-milestone";return""}
function normalizeLabel(value:string){return value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase()}
function listKindAtLine(content:string,line?:number):ListKind{if(!line)return"default";const lines=content.split("\n");for(let index=line-2;index>=0&&index>=line-16;index--){const raw=lines[index].trim();if(!raw)continue;if(/^(?:[-*+]|\d+[.)])\s/.test(raw))continue;const marker=normalizeLabel(raw.replace(/^#{1,6}\s+/,"").replace(/[*_`]/g,"").replace(/:$/,"").trim());if(marker.includes("proximas acciones")||marker.includes("proximos pasos"))return"actions";if(marker.includes("activos criticos pendientes"))return"critical-assets";if(marker.includes("proximas entregas esperadas"))return"deliveries";if(marker.includes("hito"))return"milestones";if(marker.includes("riesgo")||marker.includes("bloqueo")||marker.includes("bloquea")||marker.includes("todavia no puede"))return"risks";if(marker.includes("actividad")||marker.includes("puede comenzar"))return"activities";if(marker.includes("entregable"))return"deliverables";if(marker.includes("dependencia"))return"dependencies";if(/^#{1,6}\s/.test(raw)||/^\*\*.+\*\*/.test(raw))return"default";}return"default"}
export function MarkdownRenderer({content}:{content:string}){return <article className="prose-project"><ReactMarkdown remarkPlugins={[remarkGfm]} rehypePlugins={[rehypeSlug,[rehypeAutolinkHeadings,{behavior:"wrap"}]]} components={{p({children}){const text=childrenText(children);const match=text.match(STATUS);return match?<StatusBadge symbol={match[1] as "🟢"} text={match[2]}/>:<p className={calloutClass(text)}>{children}</p>},ul({children,node,...props}){const kind=listKindAtLine(content,node?.position?.start.line);return <ul {...props} role="list" className={`markdown-list markdown-list-${kind}`}>{children}</ul>},ol({children,node,...props}){const kind=listKindAtLine(content,node?.position?.start.line);return <ol {...props} className={`markdown-list markdown-list-ordered markdown-list-${kind}`}>{children}</ol>},td({children}){const text=childrenText(children);const match=text.match(STATUS);return <td>{match?<StatusBadge symbol={match[1] as "🟢"} text={match[2]}/>:RACI.test(text)?<span className={`raci-badge raci-${text.toLowerCase()}`}>{text}</span>:children}</td>}}}>{content}</ReactMarkdown></article>}
